### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio-community/node-edgedriver#13]
Hey @barretts,

first off, thank you for making the package and simplify consuming the Edgedriver binaries through Node.js.

I was curious if this package is still maintained as it hasn't seen any update for 4 years. We are using this in the WebdriverIO project and would be interested taking over maintenance of this if you aren't planing to do any work around this project anymore.

Please let me know.

Cheers

**Comment by barretts** [comment]
Yes that would work for me. I'm looking at how to handle it; if you've already got some ideas please share!

**Comment by christian-bromann** [comment]
Thank you for getting back to me.

I just invited you to the [`webdriverio-community`](https://github.com/webdriverio-community) or and I would suggest this:
- transfer the package to that org so other WDIO contributor can push and release new versions
- add [`wdio-user`](https://www.npmjs.com/~wdio-user) to the list of maintainer on NPM so we can set up a release pipeline

Would that work for you?

**Comment by barretts** [comment]
Is webdriverio interested in https://github.com/barretts/node-iedriver as well? I don't know if that will ever be updated again since I'm happily not supporting IE anymore.

**Comment by christian-bromann** [comment]
> Is webdriverio interested in https://github.com/barretts/node-iedriver as well?

Thanks for offering but IMO IE is dead at this point and there is no value continue to maintain it.

**Comment by barretts** [comment]
Done and done. Let me know if you need anything else!

**Comment by christian-bromann** [comment]
Thank you @barretts!

**Comment by christian-bromann** [comment]
@barretts it seems that [`~wdio-user`](https://www.npmjs.com/~wdio-user) is still not package maintainer on NPM, could you add that user so we can release the package?

**Comment by barretts** [comment]
Sorry the NPM page shows that wdio-user never accepted my invitation. But that also means the invite has been sitting there for a long while. I can always rescind the invitation and do it again if you'd like.

**Comment by christian-bromann** [comment]
> I can always rescind the invitation and do it again if you'd like.

Please send the invite again, I couldn't find any email in my inbox.

**Comment by barretts** [comment]
I'm guessing that you still haven't received the invitation? To be sure I was inviting wdio-user as a maintainer.

**Comment by christian-bromann** [comment]
Yes, I sent you an email this morning mentioning that I unfortunately had an invalid email set for the account and requested to resend the invite for one more time. Sorry for the confusions.

**Comment by christian-bromann** [comment]
We have access to the NPM package now, thanks @barretts
